### ISSUE TITLE
Cloudflare cache purge upon deploying new image

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Frontend#100]
Because of how good Cloudflare is at caching, people who have visited padma.io before, would still today see the old version :P So it is a good reminder that actually the correct way for a service like this frequent small updates to the structure but not much in terms of actual content, is to purge everything upon deploy.

**Comment by blahmonkey** [comment]
Ah, I saw this ticket earlier. I think the standard way used elsewhere was to ping the CF API on CD to production...let me ask @pdey to do this ?

**Comment by mikkokotila** [comment]
Here is a code-snippet we can use to do it: 

```
    if (!process.env.CLOUDFLARE_CACHE_API_KEY) {
      console.warn('Cache purge bypassed!');
      return Promise.resolve();
    }
    console.log(`Cache purge zone (${zoneID}) URls:`);
    console.log(urls);
    return axios.post(`${API_BASE_URL}/zones/${zoneID}/purge_cache`,
      { files: urls },
      {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${process.env.CLOUDFLARE_CACHE_API_KEY}`,
        },
      });
  },
```

**Comment by blahmonkey** [comment]
@pdey Can you look at this one? I think it should be integrated with the CD to production

**Comment by mikkokotila** [comment]
Looks like there is a better way to do this, we can do it inside Github Action: 

```
    # Purge all cached assets on CF
    - name: Cloudflare Purge Cache (cav.ai)
      uses: MrHakala/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_API_KEY }}
        PURGE_HOSTS: '["padma.io"]'
```
